[package]
name = "bevy_pathmesh"
version = "0.3.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
polyanya = "0.2.1"
itertools = "0.10.5"

[dependencies.bevy]
version = "0.9.0"
features = ["bevy_sprite", "bevy_render", "bevy_ui", "bevy_text", "bevy_core_pipeline", "bevy_winit", "bevy_asset", "bevy_scene"]
default-features = false

[dev-dependencies]
bevy_prototype_debug_lines = "0.8"
rand = "0.8"

[features]
default = []
linuxci = ["bevy/x11"]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
bevy_prototype_debug_lines = { git = "https://github.com/ManevilleF/bevy_debug_lines", branch = "feat/bevy0.9" }
