[package]
name = "bevy_pathmesh"
version = "0.3.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["pathfinding", "bevy", "navmesh"]
readme = "README.md"
description = "Navmesh plugin for Bevy"
repository = "https://github.com/vleue/bevy_pathmesh"
homepage = "https://github.com/vleue/bevy_pathmesh"
documentation = "https://docs.rs/bevy_pathmesh"
categories = ["game-development"]

[dependencies]
itertools = "0.10.5"

[dependencies.polyanya]
version = "0.2.1"

[dependencies.bevy]
version = "0.9.0"
features = ["bevy_render", "bevy_asset"]
default-features = false

[dev-dependencies]
bevy_prototype_debug_lines = "0.9"
rand = "0.8"

[dev-dependencies.bevy]
version = "0.9.0"
features = ["bevy_ui", "bevy_text", "bevy_winit", "bevy_core_pipeline", "bevy_scene", "bevy_gltf"]
default-features = false

[features]
default = []
linuxci = ["bevy/x11"]

[profile.dev.package."*"]
opt-level = 3
