[package]
name = "bevy_pathmesh"
version = "0.5.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["pathfinding", "bevy", "navmesh"]
readme = "README.md"
description = "Navmesh plugin for Bevy"
repository = "https://github.com/vleue/bevy_pathmesh"
homepage = "https://github.com/vleue/bevy_pathmesh"
documentation = "https://docs.rs/bevy_pathmesh"
categories = ["game-development"]

[dependencies]
itertools = "0.11"
tracing = { version = "0.1", optional = true }

[dependencies.polyanya]
version = "0.4"
# path = "../polyanya"
git = "https://github.com/vleue/polyanya"
branch = "radius-baking"

[dependencies.bevy]
version = "0.12"
features = ["bevy_render", "bevy_asset"]
default-features = false

[dev-dependencies]
rand = "0.8"

[dev-dependencies.bevy]
version = "0.12"
features = [
    "bevy_ui",
    "bevy_text",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_scene",
    "bevy_gltf",
    "bevy_pbr",
    "bevy_sprite",
    "bevy_gizmos",
    # Required for TonyMcMapface
    "tonemapping_luts",
    "ktx2",
    "zstd",
]
default-features = false

[features]
default = []
linuxci = ["bevy/x11"]

[profile.dev.package."*"]
opt-level = 3

[workspace]
members = ["examples/interactive", "examples/physics_xpbd"]
