[package]
name = "navmesh"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
bevy = { version = "0.4", default-features = false, features = ["bevy_winit", "render", "bevy_wgpu", "bevy_gltf"] }
petgraph = "0.5"

[dev-dependencies]
rand = "0.8"

[features]
default = []
linuxci = ["bevy/x11"]

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
